 # The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
    modLoader="javafml"
    # A version range to match for said mod loader - for regular FML @Mod it will be the forge version
    # Forge for 1.14.4 is version 28
    loaderVersion="[47,)"
    # If the mods defined in this file should show as seperate resource packs
    showAsResourcePack=false
    
    license="MIT"


    [[mods]]
      modId="llamamod"
      version="1.0.0.0"
      displayName="llama mod"
      displayURL="minecraftforge.net"
      credits="I'd like to thank my mother and father."
      authors="Author"
      description='''
    become llama
      '''

      [[dependencies.examplemod]]
        modId="forge"
        mandatory=true
        versionRange="[47,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.examplemod]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.20.1]"
        ordering="NONE"
        side="BOTH"