    modLoader="javafml"
   
    loaderVersion="[47,)"

    showAsResourcePack=false
    
    license="MIT"

    [[mods]]
      modId="llamamod"
      version="1.0.0.0"
      displayName="llama mod"
      displayURL="minecraftforge.net"
      credits="I'd like to thank my mother and father."
      authors="Author"
      description='''
    become llama
      '''

      [[dependencies.examplemod]]
        modId="forge"
        mandatory=true
        versionRange="[47,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.examplemod]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.20.1]"
        ordering="NONE"
        side="BOTH"